version: '3.4'

services:
  pgdb:
    image: postgres

  orderingapi:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: OrderingApi/Dockerfile

  productapi:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: ProductApi/Dockerfile

volumes:
  postgres_data:
  pgadmin_data: